server:
  port: 8001

spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: replanetorg@gmail.com
    password: zlvm wtcl qyej pbxe
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com
      mail.smtp.starttls.enable: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/replanet
    username: root
    password: 74320305
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB


  logging:
    level:
      org.hibernate: info
      org.hibernate.SQL: debug
      org.hibernate.type: trace

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 8a5a93627a69a5b1728721bc6ff53635
            redirect-uri: http://localhost:3000/oauth/kakao
#            client-secret: TcYhrxzWSY1frhLvSUpKcYAwDd5pUw6hJ9nTofayKEFBluK64yQnrsJlffIKPXVaAAABi7KTyJAicpf3YNJZ6g
            scope: account_email
            authorization-grant-type: authorization_code
            client-name: Kakao
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  key: dkjkla23djflka123djflk23420394rjglasdkgljdl
  time: 86400000
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
coolsms:
  api:
    key: "NCSCXEQPTW0K6AEB"
    secret: "O6TTAGTY5UCH84C19UUL9W6QLWSHJ4KG"

jasypt:
  encryptor:
    password: 4u5u4j2#u4h32uih4D72*+kfduffsa&%r3uQ^JHNUEY7
