// 회원가입
#POST http://localhost:8001/auth/signup
#Content-Type: application/json
#
#{
#  "email": "ddd",
#  "password": "1234",
#  "phone": "010-1234-5678",
#  "memberName": "김민주"
#}

GET https://kauth.kakao.com/oauth/authorize?client_id=5a90ac83e3e59ba52ef0c472bc65e3e0&redirect_uri=http://localhost:8001/login/oauth2/code/kakao&response_type=code
// 로그인
POST http://localhost:8001/auth/login
Content-Type: application/json

{
  "email": "admin",
  "password": "1234"
}

